apiVersion: v1
kind: Service
metadata:
  name:  {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: resumemanagement
    app.kubernetes.io/instance: {{ .Release.Name }}
    hhh: helmdeployedservice
spec:
  type: NodePort
  selector:
    app: DFW
    app.kubernetes.io/name: resumemanagement
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: webappadmin
      port: {{ .Values.webappmainPort }}
      targetPort: 8700
      NodePort : 30007
    - name : imageserver
      port: {{ .Values.imageserverPort }}
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 8770
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30008