apiVersion: v1
kind: Service
metadata:
  name: db-fs-app
spec:
  type: NodePort
  selector:
    app: DFW
  ports:
    - name : webappmain
      port: 8700
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 8700
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
    - name : imageserver
      port: 8770
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 8770
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30008
    - name : practice
      port: 8010
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 8010
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30009